version: "3.8"
services:
  server:
    container_name: to-do-django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ".env"
    depends_on:
      - database

  database:
    container_name: to-do-django-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: to_do_db
    volumes:
      - database-data:/var/lib/postgresql/data

  nginx:
    container_name: to-do-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf.d:/etc/nginx/nginx-conf.d
      - static:/app/static
      - media:/app/media
    depends_on:
      - server

volumes:
  static:
  media:
  database-data:
